const $=s=>document.querySelector(s),state={items:[],keywords:[],reviews:{}};
const REPO="Dranawor/SMSearcher";
async function getJson(path,fallback){try{const r=await fetch(`${path}?${Date.now()}`);return r.ok?await r.json():fallback}catch{return fallback}}
async function load(){try{const d=await getJson("data/results.json",null);if(!d)throw Error("No scan data is available yet.");state.items=d.items||[];state.keywords=d.keywords||[];state.reviews=await getJson("data/reviews.json",{});$("#last-scan").textContent=d.scan?.completed_at?new Date(d.scan.completed_at).toLocaleString():"—";$("#keyword-count").textContent=state.keywords.length;$("#match-count").textContent=state.items.length;$("#new-count").textContent=state.items.filter(x=>x.is_new).length;updateStats();for(const k of state.keywords){const o=document.createElement("option");o.value=k;o.textContent=k;$("#keyword").append(o)}render()}catch(e){$("#message").textContent=e.message}}
function reviewed(x){return Boolean(state.reviews[String(x.id)]?.reviewed)}
function updateStats(){const n=state.items.filter(x=>!reviewed(x)).length;$("#unreviewed-count").textContent=n;$("#reviewed-count").textContent=state.items.length-n}
function issueUrl(x,action="REVIEW"){const title=`[${action}] ${x.id} — ${x.title||"Workshop listing"}`;const body=[`Workshop listing: ${x.url}`,`Workshop ID: ${x.id}`,`Title: ${x.title||"Untitled"}`,`Keywords: ${(x.keywords||[]).join(", ")}`,"","Review note:","","---","This issue is used by SMSearcher to maintain the shared review queue."].join("\n");return `https://github.com/${REPO}/issues/new?title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}`}
function render(){const q=$("#q").value.toLowerCase().trim(),k=$("#keyword").value,s=$("#status").value;const a=state.items.filter(x=>{const h=[x.title,x.creator,x.description,...(x.keywords||[])].join(" ").toLowerCase(),r=reviewed(x);return(!q||h.includes(q))&&(!k||(x.keywords||[]).includes(k))&&(s==="all"||(s==="new"&&x.is_new)||(s==="unreviewed"&&!r)||(s==="reviewed"&&r))});$("#message").style.display=a.length?"none":"block";$("#results").innerHTML=a.map(x=>{const r=state.reviews[String(x.id)],img=safeImage(x.thumbnail);return `<article class="card ${r?"reviewed":""}"><div class="preview">${img?`<img class="thumb" src="${img}" alt="" loading="lazy">`:`<div class="thumb placeholder">No preview</div>`}<div class="card-main"><div class="card-head"><div><div class="title">${esc(x.title||"Untitled")}</div><div class="meta">${esc(x.creator||"Unknown creator")}</div></div><div class="meta">${x.is_new?'<span class="tag new">NEW</span> ':''}${r?'<span class="tag reviewed-tag">REVIEWED</span>':''}</div></div><div class="tags">${(x.keywords||[]).map(k=>`<span class="tag">${esc(k)}</span>`).join("")}</div><div class="description">${x.description?esc(x.description.slice(0,420))+(x.description.length>420?"…":""):"No description available."}</div>${r?`<div class="review-info">Reviewed by <strong>${esc(r.reviewer||"team member")}</strong>${r.reviewed_at?` on ${esc(new Date(r.reviewed_at).toLocaleString())}`:""}${r.note?`<div>${esc(r.note)}</div>`:""}</div>`:""}<div class="actions"><a class="button primary" href="${safe(x.url)}" target="_blank" rel="noopener">Open Steam ↗</a>${r?`<a class="button secondary dark" href="${issueUrl(x,"UNREVIEW")}" target="_blank" rel="noopener">Undo Reviewed</a>`:`<a class="button review" href="${issueUrl(x)}" target="_blank" rel="noopener">Mark Reviewed</a>`}</div></div></div></article>`}).join("")}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function safe(u){try{const x=new URL(u);return x.protocol==="https:"&&x.hostname==="steamcommunity.com"?x.href:"#"}catch{return"#"}}
function safeImage(u){try{const x=new URL(u);return x.protocol==="https:"&&(x.hostname==="steamuserimages-a.akamaihd.net"||x.hostname.endsWith(".steamusercontent.com")||x.hostname==="steamcommunity.com")?x.href:""}catch{return""}}
["q","keyword","status"].forEach(id=>$("#"+id).addEventListener("input",render));load();
